language: ruby
rvm:
- 2.6.3
cache:
  bundle: true
  yarn: true
  directories:
    - node_modules
install:
  - bundle install
services:
  - postgresql
script:
  - bundle exec rake db:migrate:reset RAILS_ENV=test
  - bundle exec rspec

