language: ruby
rvm:
- 2.6.3
install:
  - bundle install
  - yarn add bootstrap jquery popper.js
services:
  - postgresql
script:
  - bundle exec rake db:migrate:reset RAILS_ENV=test
  - bundle exec rspec

